"Resource/UI/HudDamageAccount.res"
{
	"CDamageAccountPanel"
	{
		"fieldName"				"CDamageAccountPanel"
		"text_x"				"0"
		"text_y"				"0"
		"delta_item_end_y"		"0"
		"PositiveColor"			"0 255 0 255"
		"NegativeColor"			"255 225 0 255"
		"delta_lifetime"		"2.0"
		"delta_item_font"		"DamagePopUp"
		"delta_item_font_big"	"DamagePopUpCrit"
	}	
	"DamageAccountValue"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"DamageAccountValue"
		"xpos"				"c-26"
		"ypos"				"71"
		"zpos"				"2"
		"wide"				"52"
		"tall"				"30"
		"border"			"TFThinLineBorder"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%metal%"
		"textAlignment"		"center"
		"fgcolor"			"0 255 0 255"
		"font"				"HudFontMediumBold"
	}
	"DamageAccountValueShadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"DamageAccountValueShadow"
		"xpos"				"c-25"
		"ypos"				"72"
		"zpos"				"2"
		"wide"				"52"
		"tall"				"30"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%metal%"
		"textAlignment"		"center"
		"fgcolor"			"0 0 0 255"
		"font"				"HudFontMediumBold"
	}
	"HitIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HitIcon"
		"xpos"			"c-9"
		"ypos"			"60"
		"zpos"			"6"
		"wide"			"18"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"image"			"replay/thumbnails/hud/hit_icon"
		"scaleImage"	"1"
	}
	"HealPlus"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"HealPlus"
		"xpos"				"c-21"
		"ypos"				"74"
		"zpos"				"3"
		"wide"				"20"
		"tall"				"20"
		"labelText"			"+"
		"font"				"HudFontMediumBold"
		"fgcolor"			"Green"
		"textAlignment"		"North-west"
		"visible"			"1"
		"enabled"			"1"
		"alpha"				"255"
	}
	"HealPlusShadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"HealPlusShadow"
		"xpos"				"c-20"
		"ypos"				"75"
		"zpos"				"3"
		"wide"				"20"
		"tall"				"20"
		"labelText"			"+"
		"font"				"HudFontMediumBold"
		"fgcolor"			"0 0 0 255"
		"textAlignment"		"North-west"
		"visible"			"1"
		"enabled"			"1"
		"alpha"				"255"
	}
}