"Resource/UI/HudDemomanPipes.res"
{
	"background"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"background"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"0"
		"wide"				"86"
		"tall"				"40"
		"visible"			"1"
		"visible_minmode"	"1"
		"enabled"			"1"
		"image"				"replay/thumbnails/hud/effectmeterrightred"
		"scaleImage"		"1"	
		"teambg_2"			"replay/thumbnails/hud/effectmeterrightred"
		"teambg_2_minmode"	"replay/thumbnails/hud/minmode/effectmeterrightred"
		"teambg_2_lodef"	"replay/thumbnails/hud/effectmeterrightred"
		"teambg_3"			"replay/thumbnails/hud/effectmeterrightblu"
		"teambg_3_minmode"	"replay/thumbnails/hud/minmode/effectmeterrightblu"
		"teambg_3_lodef"	"replay/thumbnails/hud/effectmeterrightblu"				
	}
	
	"ChargeLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"ChargeLabel"
		"xpos"					"4"
		"ypos"					"18"
		"xpos_minmode"			"4"
		"ypos_minmode"			"18"
		"zpos"					"2"
		"wide"					"51"
		"tall"					"15"
		"autoResize"			"1"
		"pinCorner"				"2"
		"visible"				"1"
		"visible_minmode"		"1"
		"textAlignment_minmode"	"center"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#TF_Charge"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"fgcolor_override"		"white"
		"font"					"ChalkboardText2"
	}

	"ChargeMeter"
	{	
		"ControlName"			"ContinuousProgressBar"
		"fieldName"				"ChargeMeter"
		"font"					"Default"
		"xpos"					"10"
		"ypos"					"13"
		"xpos_minmode"			"10"
		"ypos_minmode"			"13"
		"zpos"					"2"
		"wide"					"36"
		"wide_minmode"			"36"
		"tall"					"5"				
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"textAlignment"			"Left"
		"dulltext"				"0"
		"brighttext"			"0"
	}				
		
	"PipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"PipesPresentPanel"
		"xpos"			"-17"
		"ypos"			"-7"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"24"
			"ypos"			"15"
			"ypos_minmode"	"15"
			"wide"			"23"
			"wide_minmode"	"23"
			"tall"			"23"
			"tall_minmode"	"23"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../vgui/class_icons/no_border_demo_icon"
			"scaleImage"	"1"
			"teambg_2"		"../vgui/class_icons/no_border_demo_icon"
			"teambg_3"		"../vgui/class_icons/no_border_demo_icon"
		}	
		
		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"38"
			"ypos"			"15"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"25"
			"tall_lodef"	"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"fgcolor"		"TanLight"
			"font"			"HudFontMediumSmall"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"39"
			"ypos"			"16"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"25"
			"tall_lodef"	"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"fgcolor"		"black"
			"font"			"HudFontMediumSmall"
		}		
	}
	
	"NoPipesPresentPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"NoPipesPresentPanel"
		"xpos"			"-17"
		"ypos"			"-7"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		
		"PipeIcon"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PipeIcon"
			"xpos"			"24"
			"ypos"			"15"
			"ypos_minmode"	"15"
			"wide"			"23"
			"wide_minmode"	"23"
			"tall"			"23"
			"tall_minmode"	"23"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../vgui/class_icons/no_border_demo_icon"
			"scaleImage"	"1"
			"teambg_2"		"../vgui/class_icons/no_border_demo_icon"
			"teambg_3"		"../vgui/class_icons/no_border_demo_icon"
		}

		"NumPipesLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabel"
			"xpos"			"38"
			"ypos"			"15"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"25"
			"tall_lodef"	"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"1"
			"brighttext"	"0"
			"fgcolor"		"TanLight"
			"font"			"HudFontMediumSmall"
		}
		"NumPipesLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"NumPipesLabelDropshadow"
			"xpos"			"39"
			"ypos"			"16"
			"zpos"			"2"
			"wide"			"35"
			"tall"			"25"
			"tall_lodef"	"20"
			"autoResize"	"1"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"%activepipes%"
			"textAlignment"	"center"
			"dulltext"		"1"
			"brighttext"	"0"
			"fgcolor"		"black"
			"font"			"HudFontMediumSmall"
		}			
	}				
}
